### PR TITLE
Fix `egui` feature compilation error 

### PR DESCRIPTION
**Pull request by devil-ira**
Fixes a compile error with the `egui` feature enabled when the `ui` or `block_ui_interactions` features are disabled.

### CODE REVIEW

**Comment by WesleyClements** [comment]
I've looked into the tests failing a bit and it seems that changing the mouse_motion to a Vec is preventing app.send_input from doing anything. Specifically, the MouseMotion is being created but not propagated back into update_action_state because self.mouse_motion.push is a mutation on a copy of the data.

**Comment by WesleyClements** [comment]
I addressed the failing tests in #424 but do make sure that the changes I made make sense

**Comment by alice-i-cecile** [comment]
You're both great: thank you. I'm currently sick, but I'm looking to sit down with LWIM later this week and fix stuff up.

**Review by alice-i-cecile — APPROVED** [review]
